config/routes.rb
Rails.application.routes.draw do
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    
    
  resources :books
  resources :spells
  resources :books_spells
    
  root to: 'static_pages#home'
    
  get 'books/:id/confirm_delete', to: 'books#confirm_delete', as: 'confirm_delete_book'

  get 'spells/:id/confirm_delete', to: 'spells#confirm_delete', as: 'confirm_delete_spell'
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    has_and_belongs_to_many :spells
    validates_presence_of :name
    validates_length_of :name, maximum: 70 
    
    def self.order_by field
      return Book.order(:name)
    end
    
    
end

app/models/spell.rb
class Spell < ApplicationRecord
    has_and_belongs_to_many :books, dependent: :destroy
    validates_presence_of :name
    validates_uniqueness_of :name, case_sensitive: false
    validates_length_of :name, maximum: 70 
    validates_presence_of :level
    validates_presence_of :school
    validates_presence_of :concentration
    validates_length_of :description, maximum: 4096
    
    def self.order_by field
      return Spell.order(:level, :name)
    end
    
=begin
    def self.order_by field
        return @spells.sort_by {|x| [x.level, x.name] }
    end
=end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    
  def index
      @books = Book.order_by params[:order_by]
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      flash[:notice] = 'Book was successfully created.'  
      redirect_to @book
    else
      render :new
    end
      
  end

  def new
      @book = Book.new
  end

  def edit
       @book = Book.find(params[:id])
  end

  def show
      @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])  
    if @book.update(book_params)
      flash[:notice] = 'Book was successfully updated.' 
      redirect_to @book
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])  
    if @book.destroy
        flash[:notice] = 'Book was successfully deleted.'
    else
        flash[:notice] = 'Unable to delete book.'
    end
    redirect_to books_url
  end
    
    
    
    
    private
    # Only allow a trusted parameter "white list" through.
    def book_params
      # params is a hashtable.  It should have in it a key of :book.
      # The value for the :book key is another hash.
      # If params does not contain the key :book, an exception is raised.  
      # Only the "book" hash is returned and only with the permitted key(s).
      # So returns a hash with only having at most keys of :title, :year, :author_id
      params.require(:book).permit(:name)
    end
    
    
    
end

app/controllers/spells_controller.rb
class SpellsController < ApplicationController
  def index
       @spells = Spell.order_by params[:order_by]
  end

  def create
      @spell = Spell.new(spell_params)

      if @spell.save
          flash[:notice] = 'Spell was successfully created.'  
          redirect_to @spell
      else
          render :new
      end
  end

  def new
        @spell = Spell.new
  end

  def edit
       @spell = Spell.find(params[:id])
  end

  def show
      @spell = Spell.find(params[:id])
  end

  def update
     @spell = Spell.find(params[:id])  
    if @spell.update(spell_params)
      flash[:notice] = 'Spell was successfully updated.' 
      redirect_to @spell
    else
      render :edit
    end
   
  end

  def destroy
    @spell = Spell.find(params[:id])  
    if @spell.destroy
        flash[:notice] = 'Spell was successfully deleted.'
    else
        flash[:notice] = 'Unable to delete spell.'
    end
    redirect_to spells_url
  end
    
     private
    # Only allow a trusted parameter "white list" through.
    def spell_params
      # params is a hashtable.  It should have in it a key of :book.
      # The value for the :book key is another hash.
      # If params does not contain the key :book, an exception is raised.  
      # Only the "book" hash is returned and only with the permitted key(s).
      # So returns a hash with only having at most keys of :title, :year, :author_id
      params.require(:spell).permit(:name, :level, :school, :concentration, :description)
       
    end
    
    
end

=begin
class BooksController < ApplicationController

  # GET /books
  def index
    # We've added a method, self.order_by, to the Book model, 
    # see models/book.rb
    @books = Book.order_by params[:order_by]
  end

  # GET /books/:id
  def show
    @book = Book.find(params[:id])
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/:id/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  def create
    @book = Book.new(book_params)

    if @book.save
      flash[:notice] = 'Book was successfully created.'  
      redirect_to @book
    else
      render :new
    end
  end

  # PATCH/PUT /books/:id
  def update
    @book = Book.find(params[:id])  
    if @book.update(book_params)
      flash[:notice] = 'Book was successfully updated.' 
      redirect_to @book
    else
      render :edit
    end
  end

  # DELETE /books/:id
  def destroy
    @book = Book.find(params[:id])  
    if @book.destroy
        flash[:notice] = 'Book was successfully deleted.'
    else
        flash[:notice] = 'Unable to delete book.'
    end
    redirect_to books_url 
  end

  private
    # Only allow a trusted parameter "white list" through.
    def book_params
      # params is a hashtable.  It should have in it a key of :book.
      # The value for the :book key is another hash.
      # If params does not contain the key :book, an exception is raised.  
      # Only the "book" hash is returned and only with the permitted key(s).
      # So returns a hash with only having at most keys of :title, :year, :author_id
      params.require(:book).permit(:title, :year, :author_id)
    end
      
end

=end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/spells_helper.rb
module SpellsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Confirm Delete</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= render 'form', book: @book %>

<p>
<%= link_to 'Show Books', books_path %> |
<%= link_to 'Home', root_path %> 
</p>

app/views/books/index.html.erb
<p id="notice"><%= flash[:notice] %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th><%= link_to 'Name', books_path(order_by: 'name') %></th>
     
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td> 
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= form_with model: book, method: :delete, local: true do |f| %>
            <%= f.submit 'Delete' %>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<p>
<%= link_to 'New Book', new_book_path %> |
<%= link_to "Home", root_path %>    
</p>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<p>
<%= link_to 'Show Books', books_path %> |
<%= link_to 'Home', root_path %> 
</p>

app/views/books/show.html.erb
<p id="notice"><%= flash[:notice] %></p>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<% @book.spells.each do |spell| %>
      <tr>
        <td><%= link_to "#{spell.name}", spell %></td>
        <td><%= link_to 'Edit', edit_spell_path(spell) %></td>
        <td><%= form_with model: spell, method: :delete, local: true do |f| %>
            <%= f.submit 'Remove spell' %>
            <% end %>
        </td>
      </tr>
    <% end %>

<p>
<%= link_to 'Edit Book', edit_book_path(@book) %> |
<%= link_to 'Show Books', books_path %> |
<%= link_to "Home", root_path %>    
</p>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spellmanager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/spells/_form.html.erb
<%= form_with(model: spell, local: true) do |form| %>
  <% if spell.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(spell.errors.count, "error") %> prohibited this spell from being saved:</h2>

      <ul>
        <% spell.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

<div class="field">
    <%= form.label :level %>
    <%= form.select(:level, [0,1,2,3,4,5,6,7,8,9]) %>
  </div>

<div class="field">
    <%= form.label :school %>
    <%= form.select(:school,['Conjuration','Necromancy','Evocation','Abjuration', 'Transmutation','Divination','Enchantment','Illusion']) %>
  </div>

<div class="field">
    <%= form.label :concentration %>
    <%= form.radio_button(:concentration, 'Yes')  %>
    <%= label_tag(:age_child, "Yes") %>  
    <%= form.radio_button(:concentration, 'No')  %>
    <%= label_tag(:age_child, "No") %>
  </div>

<div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>


<% end %>

app/views/spells/create.html.erb
<h1>Spells#create</h1>
<p>Find me in app/views/spells/create.html.erb</p>

app/views/spells/destroy.html.erb
<h1>Spells#destroy</h1>
<p>Find me in app/views/spells/destroy.html.erb</p>

app/views/spells/edit.html.erb
<h1>Edit Spell</h1>

<%= render 'form', spell: @spell %>

<p>
<%= form_with model: @spell, method: :delete, local: true do |f| %>
  <%= f.submit 'Delete spell' %>
  <% end %>
</p>

<p>
<%= link_to 'Show Spells', spells_path %> |
<%= link_to 'Home', root_path %> 
</p>


 

app/views/spells/index.html.erb
<p id="notice"><%= flash[:notice] %></p>

<h1>Spells</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @spells.each do |spell| %>
      <tr>
        <td><%= link_to "#{spell.name}", spell %></td>
        <td><%= spell.level %></td>
        <td><%= link_to 'Edit', edit_spell_path(spell) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<p>
<%= link_to 'New Spell', new_spell_path %> |
<%= link_to "Home", root_path %>    
</p>

app/views/spells/new.html.erb
<h1>New Spell</h1>

<%= render 'form', spell: @spell %>

<p>
<%= link_to 'Show Spells', spells_path %> |
<%= link_to 'Home', root_path %> 
</p>

app/views/spells/show.html.erb
<p id="notice"><%= flash[:notice] %></p>

<p>
  <strong>Name:</strong>
  <%= @spell.name %>
</p>

<p>
  <strong>Level:</strong>
  <%= @spell.level %>
</p>

<p>
  <strong>School:</strong>
  <%= @spell.school %>
</p>

<p>
  <strong>Concentration:</strong>
  <%= @spell.concentration %>
</p>

<p>
  <strong>Description:</strong>
  <%= @spell.description %>
</p>

<p>
<%= link_to 'Edit Spell', edit_spell_path(@spell) %> |
<%= link_to 'Show Spells', spells_path %> |
<%= link_to "Home", root_path %>    
</p>

app/views/spells/update.html.erb
<h1>Spells#update</h1>
<p>Find me in app/views/spells/update.html.erb</p>

app/views/static_pages/home.html.erb
<h1>Spellmanager 🔮</h1>

<p><%= link_to "Spells 🧙", spells_path %></p>
<p><%= link_to "Books 📜", books_path %></p>